import 'package:flutter/material.dart';
import 'package:mobile/theme/settings_provider.dart';
import 'package:provider/provider.dart';

class AppLocalizations {
  static String of(BuildContext context, String key, {bool listen = true}) {
    final settings = Provider.of<SettingsProvider>(context, listen: listen);
    final isBulgarian = settings.locale.languageCode == 'bg';
    final values = isBulgarian ? bg : en;
    return values[key] ?? key;
  }

  static const Map<String, String> en = <String, String>{
    'app_name': 'LostMost',
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'save': 'Save',
    'error': 'Error',
    'success': 'Success',
    'loading': 'Loading...',
    'retry': 'Retry',

    'nav_home': 'Home',
    'nav_search': 'Search',
    'nav_settings': 'Settings',

    'home_title': 'RSSI Viewer',
    'connecting': 'Connecting...',
    'proximity_close': 'Close',
    'proximity_nearby': 'Nearby',
    'proximity_far': 'Far',

    'search_title': 'Search',
    'search_page': 'Search Page',

    'login_title': 'Login',
    'login_subtitle': 'Welcome back',
    'email': 'Email',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'login_button': 'Login',
    'signup_button': 'Sign Up',
    'no_account': "Don't have an account? Sign Up",
    'have_account': 'Already have an account? Login',
    'passwords_mismatch': "Passwords don't match",
    'forgot_password': 'Forgot Password?',
    'email_required': 'Email is required',
    'invalid_email': 'Invalid email address',
    'password_required': 'Password is required',
    'password_too_short': 'Password must be at least 6 characters',
    'confirm_password_required': 'Please confirm your password',
    'generic_auth_error': 'Authentication failed. Please try again.',

    'profile_title': 'Profile',
    'account': 'Account',
    'appearance': 'Appearance',
    'theme': 'Theme',
    'system': 'System',
    'light': 'Light',
    'dark': 'Dark',
    'choose_look': 'Choose how the app looks to you',
    'language': 'Language',
    'app_language': 'App Language',
    'data_storage': 'Data & Storage',
    'data_saver': 'Data Saver',
    'reduce_data': 'Reduce data usage',
    'clear_cache': 'Clear Cache',
    'clear_cache_confirm': 'Are you sure you want to clear the app cache?',
    'clear': 'Clear',
    'cache_cleared': 'Cache cleared successfully',
    'cache_clear_failed': 'Failed to clear cache',
    'about': 'About',
    'version': 'Version',
    'source_code': 'Source Code',
    'open_link_failed': 'Could not open link',
    'color_preview': 'Color Preview',
    'primary_color': 'Primary',
    'secondary_color': 'Secondary',
    'success_color': 'Success',
    'warning_color': 'Warning',
    'danger_color': 'Danger',
    'info_color': 'Info',
    'logout': 'Log out',
    'logout_confirm': 'Are you sure you want to log out?',
    'change_password': 'Change Password',
    'new_password': 'New Password',
    'password_updated': 'Password updated successfully',
    'password_update_failed': 'Failed to update password',
  };

  static const Map<String, String> bg = <String, String>{
    'app_name': 'LostMost',
    'cancel': 'Отказ',
    'confirm': 'Потвърди',
    'save': 'Запази',
    'error': 'Грешка',
    'success': 'Успех',
    'loading': 'Зареждане...',
    'retry': 'Опитай отново',

    'nav_home': 'Начало',
    'nav_search': 'Търсене',
    'nav_settings': 'Настройки',

    'home_title': 'RSSI Преглед',
    'connecting': 'Свързване...',
    'proximity_close': 'Близо',
    'proximity_nearby': 'Наблизо',
    'proximity_far': 'Далеч',

    'search_title': 'Търсене',
    'search_page': 'Страница за търсене',

    'login_title': 'Вход',
    'login_subtitle': 'Добре дошли отново',
    'email': 'Имейл',
    'password': 'Парола',
    'confirm_password': 'Потвърди парола',
    'login_button': 'Вход',
    'signup_button': 'Регистрация',
    'no_account': 'Нямате акаунт? Регистрирайте се',
    'have_account': 'Вече имате акаунт? Влезте',
    'passwords_mismatch': 'Паролите не съвпадат',
    'forgot_password': 'Забравена парола?',
    'email_required': 'Имейлът е задължителен',
    'invalid_email': 'Невалиден имейл адрес',
    'password_required': 'Паролата е задължителна',
    'password_too_short': 'Паролата трябва да е поне 6 символа',
    'confirm_password_required': 'Потвърдете паролата',
    'generic_auth_error': 'Грешка при удостоверяване. Опитайте отново.',

    'profile_title': 'Профил',
    'account': 'Акаунт',
    'appearance': 'Външен вид',
    'theme': 'Тема',
    'system': 'Системна',
    'light': 'Светла',
    'dark': 'Тъмна',
    'choose_look': 'Изберете как да изглежда приложението',
    'language': 'Език',
    'app_language': 'Език на приложението',
    'data_storage': 'Данни и памет',
    'data_saver': 'Икономия на данни',
    'reduce_data': 'Намаляване на използването на данни',
    'clear_cache': 'Изчистване на кеша',
    'clear_cache_confirm': 'Сигурни ли сте, че искате да изчистите кеша?',
    'clear': 'Изчисти',
    'cache_cleared': 'Кешът е изчистен успешно',
    'cache_clear_failed': 'Грешка при изчистване на кеша',
    'about': 'За приложението',
    'version': 'Версия',
    'source_code': 'Изходен код',
    'open_link_failed': 'Неуспешно отваряне на линк',
    'color_preview': 'Преглед на цветовете',
    'primary_color': 'Основен',
    'secondary_color': 'Вторичен',
    'success_color': 'Успешно',
    'warning_color': 'Внимание',
    'danger_color': 'Опасност',
    'info_color': 'Информация',
    'logout': 'Изход',
    'logout_confirm': 'Сигурни ли сте, че искате да излезете?',
    'change_password': 'Смяна на парола',
    'new_password': 'Нова парола',
    'password_updated': 'Паролата е обновена успешно',
    'password_update_failed': 'Грешка при обновяване на паролата',
  };
}
